language: csharp
solution: NewPlatform.Flexberry.ORM.ODataService.sln
install:
  - nuget restore NewPlatform.Flexberry.ORM.ODataService.sln
addons:
  apt:
    packages:
      - doxygen
script:
  - msbuild /p:Configuration=Debug NewPlatform.Flexberry.ORM.ODataService.sln
after_success:
  - test $TRAVIS_PULL_REQUEST == "false"
    && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_BRANCH == "develop")
    && bash Doxygen/update-autodoc.sh
